# -*- coding: utf-8 -*-
"""Another copy of Digital_Marketing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5UBJdhgxKY56UJ9tYJ4CNTKzgcAhXuV

## Example: Digital Marketing
https://www.kaggle.com/datasets/srolka/ecommerce-customers
* People spend time on app and website
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Ecommerce Customers.csv')
df

df.head()

# find missing data and data type
df.info()

df.describe()

"""### Exploring data

#### Multivariate analysis
"""

sns.pairplot(df)

#heatmap correlation matrix
sns.heatmap(df.corr(numeric_only=True), annot=True)

sns.scatterplot(data=df, x="Length of Membership", y="Yearly Amount Spent")